- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: M-A-J de la cache des Repository
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true
